pub const WRAPPER_SH_TEMPLATE: &str = r#"#!/bin/sh
set -eu

# Generated by `engram init` (Engram version __ENGRAM_VERSION__)
ENGRAM_VERSION="__ENGRAM_VERSION__"
ENGRAM_REPO="${ENGRAM_REPO:-lkubicek1/engram}"

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$ROOT_DIR"

ENGRAM_DIR=".engram"
BIN_DIR="$ENGRAM_DIR/bin"
BIN_PATH="$BIN_DIR/engram-v${ENGRAM_VERSION}"

mkdir -p "$BIN_DIR"

# Detect platform
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$OS" in
  linux) OS="linux" ;;
  darwin) OS="darwin" ;;
  *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
esac

case "$ARCH" in
  x86_64) ARCH="x86_64" ;;
  aarch64|arm64) ARCH="aarch64" ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

# Keep this list in sync with the release workflow.
if [ "$OS" = "linux" ] && [ "$ARCH" = "aarch64" ]; then
  echo "Unsupported platform for this Engram release: linux-aarch64" >&2
  echo "Supported: linux-x86_64, darwin-x86_64, darwin-aarch64" >&2
  exit 1
fi

ASSET="engram-${OS}-${ARCH}"
TAG="v${ENGRAM_VERSION}"

if [ ! -x "$BIN_PATH" ]; then
  CHECKSUM_URL="https://github.com/${ENGRAM_REPO}/releases/download/${TAG}/checksums.txt"
  BIN_URL="https://github.com/${ENGRAM_REPO}/releases/download/${TAG}/${ASSET}"

  tmp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t engram)
  cleanup() { rm -rf "$tmp_dir"; }
  trap cleanup EXIT INT TERM

  checksums_file="$tmp_dir/checksums.txt"
  bin_file="$tmp_dir/$ASSET"

  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$CHECKSUM_URL" -o "$checksums_file"
    curl -fsSL "$BIN_URL" -o "$bin_file"
  elif command -v wget >/dev/null 2>&1; then
    wget -q "$CHECKSUM_URL" -O "$checksums_file"
    wget -q "$BIN_URL" -O "$bin_file"
  else
    echo "Error: curl or wget is required to download Engram" >&2
    exit 1
  fi

  expected=$(grep "  $ASSET\$" "$checksums_file" | awk '{print $1}' | head -n 1)
  if [ -z "$expected" ]; then
    echo "Error: checksum entry for $ASSET not found" >&2
    exit 1
  fi

  if command -v sha256sum >/dev/null 2>&1; then
    actual=$(sha256sum "$bin_file" | awk '{print $1}')
  elif command -v shasum >/dev/null 2>&1; then
    actual=$(shasum -a 256 "$bin_file" | awk '{print $1}')
  else
    echo "Error: sha256sum or shasum is required for checksum verification" >&2
    exit 1
  fi

  if [ "$expected" != "$actual" ]; then
    echo "Error: checksum mismatch for $ASSET" >&2
    echo "Expected: $expected" >&2
    echo "Actual:   $actual" >&2
    exit 1
  fi

  chmod +x "$bin_file"
  mv "$bin_file" "$BIN_PATH"
fi

exec "$BIN_PATH" "$@"
"#;
